### PR TITLE
Complex Scheme Arrangement powered by dagre

### PR DESCRIPTION
**Pull request by seveibar**
I integrated [dagre](https://github.com/dagrejs/dagre) to compute the layout. Relates to #1 I also added some tests to check different layouts. I published to gh-pages on my fork, you can view some schemes below...

* [Simple Graph](https://www.seveibar.com/auto-arrange-plugin/tests/simple-graph/index.html)
* [Complex Graph](https://www.seveibar.com/auto-arrange-plugin/tests/complex-graph/index.html)
* [Recurrent Graph](https://www.seveibar.com/auto-arrange-plugin/tests/recurrent-graph/index.html)

The recurrent graph doesn't work well, but also doesn't completely crash.

### CODE REVIEW

**Comment by Ni55aN** [comment]
While building: `Error: 'default' is not exported by node_modules/dagre/index.js`

**Comment by seagullmouse** [comment]
Hi, I just tested this and have a couple of comments.

1. the master code crashes for my use case so this is an improvement, thanks!
2. the arrangement still isn't wonderful, there are connections that go through other nodes
3. indirectly related to this pull request, comments generated by the comment plugin do not get rearranged and are left in their old positions, although the nodes themselves are moved

Is there some extra configuration we can pass to the plugin to improve dagre's positioning?

Here is a simple example of 5 nodes where connections go straight through an existing node
Screenshot 2019-07-03 at 17 21 26


Thanks both

**Comment by seagullmouse** [comment]
Couple of minor improvements in auto-arrange.js

1: add ranksep and maybe edgesep?
2: you had the if statement back to front, now can change margins

```
nodesep: this.margin === undefined ? 50 : this.margin,
ranksep: this.margin === undefined ? 50 : this.margin
```

**Comment by Ni55aN** [comment]
image

Is it expected behavior for Dagre? It would be more convenient if the bottom node will be located on the right

**Comment by Ni55aN** [comment]
https://github.com/retejs/auto-arrange-plugin/pull/5/files#diff-cffe92d002d665f3c9254a4d32d93917R22

`layoutOptions` not used anywhere

**Comment by Ni55aN** [comment]
v0.4.0 has fixes for recurrent and other complec connections. Please check it on your examples

**Comment by Sytten** [comment]
@seveibar Are you still interested in integrating dagre, considering ELKJS licensing (and the fact that I dont want to deal with java) we are looking at an alternative backend.

**Pull request closed without merging**
