### PR TITLE
Margin issue fixed for nodes with more height. Issue #9

### PR DESCRIPTION
**Pull request by nawazishali**
Solution for #9

### CODE REVIEW

**Comment by Ni55aN** [comment]
How does changing the position of `y + = heights [j] + this.margin.y;` affect the result?

**Comment by nawazishali** [comment]
@Ni55aN According to the previous flow node was being translated to "height + margin". But now we add margin after the node has translated so the first node starts from the top most position and then margin gets added from the second node moving forward. This results in equal distance between nodes. Let me share a Codesandbox that will help you visualize the issue.

**Comment by nawazishali** [comment]
@Ni55aN Here is the [sandbox](https://codesandbox.io/s/retejs-react-renderer-auto-arrange-margin-fixed-vcs2r)

**Comment by Ni55aN** [comment]
ok, this change contains in https://github.com/retejs/auto-arrange-plugin/pull/12

**Pull request closed without merging**
